name: Сборка файла геоданных GeoSite
on:
  push:
    branches:
      - master
      
    paths-ignore:
      - "**/README.md"
      - ".gitignore"
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: GeoSite
    runs-on: ubuntu-latest
    steps:
    
      - name: Клонирование кодовой базы из репозитория GitHub
        uses: actions/checkout@v6
        with:
          path: code
          
      - name: Настройка окружения Go
        uses: actions/setup-go@v6
        with:
          go-version-file: code/go.mod
          cache-dependency-path: code/go.sum

      - name: Установка переменных окружения
        run: |
          echo "NAME=geosite-v$(date +%d.%m.%Y)" >> $GITHUB_ENV
        shell: bash

      - name: Сборка файлов geosite
        run: |
          cd code || exit 1
          go run ./ --outputdir=../
          cd ../ && rm -rf code

      - name: Отправка собранных данных в ветку «release» через Git
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add geosite_tbd.dat
          git commit -m "${{ env.NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Создание релиза и загрузка файлов
        run: |
          gh release create ${{ env.NAME }} --generate-notes --latest --title ${{ env.NAME }} ./geosite_tbd.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}